#pragma once
#include <algorithm>
#include <cmath>
#include <vector>

// ---------------------------------------------------------------------------
// Automation curves: the arithmetic that turns a beat into a parameter value
// when the movement is drawn by hand rather than generated by a modulator.
//
// A curve is a list of points. Each point pins a value to a beat, and the
// value between two points is interpolated along a shape the earlier point
// chooses. Outside the first and last point the curve holds flat, which is
// what makes a short curve usable as a one-off gesture in a long arrangement
// without having to draw the rest of the song.
//
// Why a bend rather than only straight lines
// ------------------------------------------
// A straight line between two points is the wrong shape for most of what
// automation is actually asked to do. A filter that should sit closed for four
// bars and then open over one is two thirds flat and one third steep, not a
// constant climb, and a volume fade that sounds even to the ear is not even in
// amplitude. Drawing that with straight lines takes a dozen points, and the
// dozen points are then impossible to move as a gesture. One bend per segment
// is the difference between automation that can be shaped and automation that
// can only be approximated.
//
// There is no cross studio standard here to implement, so this says plainly
// what it does rather than implying an authority it does not have. Every studio
// spells this differently: FL Studio calls it tension on a spline envelope,
// Reaper stores a bezier tension per point, Live 10.1 added a curve you drag
// out of a segment. The names and the numbers do not travel between them, and
// no file format carries them, so there is nothing to be compatible with.
//
// What the shape has to satisfy is not a matter of taste, though, and that is
// what fixes the choice:
//
//  - It must not overshoot. A bent segment has to stay between the two values
//    it joins. A spline fitted through the points (which is what a Catmull-Rom
//    or an unconstrained bezier gives) bulges past them, so a cutoff drawn to
//    reach 0.8 would briefly pass it, and a fade drawn to reach silence would
//    go below it and come back. Automation that disagrees with the line drawn
//    on the screen is the shape of bug this codebase takes most seriously.
//  - It must be monotonic within a segment, so a sweep drawn as a rise never
//    momentarily falls.
//  - It must pass exactly through its points, so the value at a point is the
//    value drawn there whatever the neighbouring bends are.
//  - Bending one way then the other way by the same amount should give mirror
//    image curves, or a bend control does not feel like one control.
//
// The function used is Schlick's bias, from Christophe Schlick, "Fast
// Alternatives to Perlin's Bias and Gain Functions", Graphics Gems IV (1994),
// which is the standard cheap way to warp a 0..1 parameter towards one end:
//
//      bias(t, a) = t / ((1/a - 2)(1 - t) + 1)
//
// It is applied to the position within the segment, and the two values are
// then mixed linearly by the warped position. Warping the position rather than
// the value is what guarantees no overshoot: the result is always a point on
// the straight line between the two values, just reached earlier or later. It
// is also one multiply, one add and one divide, with no call to pow, which
// matters because this is evaluated on the audio thread.
//
// Schlick's bias has the symmetry asked for above exactly: bias(., a) and
// bias(., 1 - a) are inverse functions, so mapping the bend onto a either side
// of a half makes +b and -b mirror images.
//
// This header is deliberately free of JUCE, so the arithmetic can be compiled
// and run under sanitizers on its own. See Tests/AutomationCurveTest.cpp.
// ---------------------------------------------------------------------------

// The mixer fader's travel. Named because automation has to map a curve onto
// it and the interface has to draw the same travel, and the two disagreeing
// would mean a fader that automation could not reach the top of.
inline constexpr float kUnityFaderGain = 0.8f;    // 0 dB
inline constexpr float kMaxFaderGain   = 1.25f;

// What kind of thing a moving value is pointed at. Here rather than beside the
// rest of the target, because which range a reading means is arithmetic and
// the arithmetic is what the tests can reach.
//
// An insert is not a plugin in a channel slot, so its own controls have to be
// named rather than indexed: a fader and a pan are not parameters of anything.
// An effect inside an insert does have indexed parameters, like an instrument,
// but needs the slot as well as the insert to find it.
enum class AutoTargetKind
{
    channelParam = 0,   // a parameter of the plugin in an instrument channel
    insertVolume,       // a mixer insert's fader
    insertPan,          // a mixer insert's pan
    insertFxParam       // a parameter of an effect in one of an insert's slots
};

/** The control value a curve reading means, for a target of this kind. A curve
    is always stored 0..1, because that is what a plugin parameter is and what
    a drawn height is; the fader and the pan have their own travel and are
    mapped onto it here, in one place, so that the engine and the interface
    cannot disagree about where the top of a fader is. */
inline float autoControlValue (AutoTargetKind kind, double curveValue) noexcept
{
    const double v = std::clamp (std::isfinite (curveValue) ? curveValue : 0.0, 0.0, 1.0);

    switch (kind)
    {
        case AutoTargetKind::insertVolume: return (float) (v * (double) kMaxFaderGain);
        case AutoTargetKind::insertPan:    return (float) (v * 2.0 - 1.0);
        case AutoTargetKind::channelParam:
        case AutoTargetKind::insertFxParam: break;
    }
    return (float) v;   // a plugin parameter is already normalised
}

/** The inverse, so that a new curve can start from wherever the control is
    sitting now rather than from zero, which is what makes drawing one on a mix
    that is already balanced not throw the balance away. */
inline double autoCurveValueFor (AutoTargetKind kind, double controlValue) noexcept
{
    if (! std::isfinite (controlValue))
        return 0.0;

    switch (kind)
    {
        case AutoTargetKind::insertVolume: return std::clamp (controlValue / (double) kMaxFaderGain, 0.0, 1.0);
        case AutoTargetKind::insertPan:    return std::clamp ((controlValue + 1.0) * 0.5, 0.0, 1.0);
        case AutoTargetKind::channelParam:
        case AutoTargetKind::insertFxParam: break;
    }
    return std::clamp (controlValue, 0.0, 1.0);
}

struct AutoCurvePoint
{
    double beat  = 0.0;    // beats from the curve's own origin
    double value = 0.0;    // normalised 0..1

    // How the segment leaving this point towards the next one is shaped.
    // Zero is a straight line. Positive holds the value near this point and
    // then runs quickly to the next, which is the "sit still, then sweep"
    // shape. Negative leaves quickly and eases into the next point. The bend
    // on the last point has no segment to shape, and is kept rather than
    // dropped so that adding a point after it does not appear to invent a
    // shape out of nowhere.
    double bend  = 0.0;    // -1..1

    bool operator== (const AutoCurvePoint&) const = default;
};

// How far the bias parameter is allowed towards its ends. At the limit the
// midpoint of a segment has moved a thirty-second of the way, which is as
// close to a hold followed by a step as a curve can get while still being a
// curve: the bias function degenerates into an actual discontinuity at zero
// and one, and a segment that jumps is a thing to draw with two points at the
// same beat, not something a bend control should stumble into at its travel
// limit.
inline constexpr double kMinAutoBendBias = 1.0 / 32.0;

// Far more points than a drawn gesture needs: this is one every sixteenth for
// sixty four bars. The cap exists so that a damaged or hostile project file
// cannot hand the audio thread a list of any length it likes.
inline constexpr size_t kMaxAutoCurvePoints = 4096;

/** The bias parameter a bend amount asks for, in (0, 1). Half is a straight
    line. Exposed because the interface draws the same curve the engine plays,
    and the two must not be able to disagree. */
inline double autoBendBias (double bend) noexcept
{
    if (! std::isfinite (bend))
        return 0.5;

    // (1 - bend) / 2 maps bend -> a and so -bend -> 1 - a, which is what makes
    // the two directions mirror images. Clamping stays symmetric about a half,
    // so they are still mirror images at the travel limit.
    const double a = (1.0 - std::clamp (bend, -1.0, 1.0)) * 0.5;
    return std::clamp (a, kMinAutoBendBias, 1.0 - kMinAutoBendBias);
}

/** Where within a segment the value has got to, given how far along the
    segment time has got. Takes 0..1 to 0..1, strictly increasing, exact at
    both ends for every bend. */
inline double autoCurveShape (double t, double bend) noexcept
{
    if (! (t > 0.0))     // also catches a NaN, which must not fall through
        return 0.0;
    if (t >= 1.0)
        return 1.0;

    const double a = autoBendBias (bend);
    const double s = 1.0 / a - 2.0;

    // The derivative of this is (s + 1) / (s(1 - t) + 1)^2, positive for every
    // s > -1, and a is clamped well inside (0, 1) so s is comfortably greater
    // than -1. That is the whole monotonicity argument.
    return t / (s * (1.0 - t) + 1.0);
}

/** Puts a point list into the form the lookup below relies on: finite, in
    range, and sorted by beat.

    The sort is stable, so two points left at the same beat keep the order they
    were given in, and the later one wins at that beat. That is a deliberate
    step rather than a degenerate case to defend against: an instant jump is
    something automation is asked for, and two points at one beat is how to say
    it. Everything else about the evaluation is indifferent to it.
*/
inline void normaliseAutoCurve (std::vector<AutoCurvePoint>& points)
{
    // Anything that is not a number goes before the sort. Sorting a list with
    // a NaN in it breaks the comparator's strict weak ordering, which is
    // undefined behaviour, and a project file is not to be trusted that far.
    points.erase (std::remove_if (points.begin(), points.end(),
                                  [] (const AutoCurvePoint& p)
                                  {
                                      return ! (std::isfinite (p.beat) && std::isfinite (p.value)
                                                && std::isfinite (p.bend));
                                  }),
                  points.end());

    for (auto& p : points)
    {
        p.value = std::clamp (p.value, 0.0, 1.0);
        p.bend  = std::clamp (p.bend, -1.0, 1.0);
    }

    std::stable_sort (points.begin(), points.end(),
                      [] (const AutoCurvePoint& a, const AutoCurvePoint& b) { return a.beat < b.beat; });

    if (points.size() > kMaxAutoCurvePoints)
        points.resize (kMaxAutoCurvePoints);
}

/** The curve's value at a beat.

    Before the first point and after the last the curve holds that point's
    value: a curve describes the span it covers and says nothing about the rest
    of the arrangement, so it must not be read as a ramp from zero.

    `fallback` is what an empty curve reads, which is the value the engine
    should leave the target at: nothing drawn means nothing automated.

    Expects a normalised list. Given an unsorted one it still returns a value
    in range rather than reading out of bounds, but which value is not defined.
*/
inline double autoCurveValueAt (const std::vector<AutoCurvePoint>& points,
                                double beat, double fallback = 0.0) noexcept
{
    if (points.empty())
        return fallback;

    if (! std::isfinite (beat))
        return points.front().value;

    // Checked before the front, so that a curve whose points all share one
    // beat reads as the last of them rather than the first.
    if (beat >= points.back().beat)
        return points.back().value;
    if (beat < points.front().beat)
        return points.front().value;

    // The last point at or before this beat. With points stacked on one beat
    // that is the last of the stack, which is what makes the step land on the
    // beat rather than a hair after it.
    const auto hi = std::upper_bound (points.begin(), points.end(), beat,
                                      [] (double b, const AutoCurvePoint& p) { return b < p.beat; });
    const auto lo = hi - 1;

    const double span = hi->beat - lo->beat;
    if (! (span > 0.0))
        return hi->value;   // unreachable with a sorted list; cheap insurance against one that is not

    // t is strictly inside (0, 1) here, because beat is strictly between the
    // two beats, but the shape function is exact at both ends anyway, so a
    // point lands on its own value whatever rounding does to this division.
    const double t = (beat - lo->beat) / span;
    return lo->value + (hi->value - lo->value) * autoCurveShape (t, lo->bend);
}

/** The last beat the curve has anything to say about, measured from its own
    origin. Zero for an empty curve. */
inline double autoCurveLastBeat (const std::vector<AutoCurvePoint>& points) noexcept
{
    return points.empty() ? 0.0 : points.back().beat;
}
